[build]
jobs = -1

[doc]
browser = "firefox-developer-edition"

[cargo-new]
vcs = "git"

[target.'cfg(all())']
rustflags = ["-Z", "share-generics=y"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "target-cpu=native"]
